# Generated by Django 5.2.16 on 2026-07-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_service', '0002_userreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreport',
            name='target_type',
            field=models.CharField(choices=[('university', 'University'), ('event', 'Event'), ('organizer', 'Organizer'), ('essay_review', 'Essay review'), ('mentorship_session', 'Mentorship session'), ('other', 'Other')], max_length=20),
        ),
    ]
