# Generated by Django 5.2.15 on 2026-06-28 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university_service', '0004_university_international_office_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('essay_type', models.CharField(choices=[('common_app', 'Common App personal statement'), ('supplement', 'Supplement'), ('scholarship', 'Scholarship'), ('activity', 'Activity description'), ('intellectual_interest', 'Intellectual interest'), ('why_major', 'Why this major'), ('why_school', 'Why this school'), ('additional_information', 'Additional information'), ('other', 'Other')], default='other', max_length=30)),
                ('prompt_text', models.TextField(blank=True)),
                ('word_limit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('draft_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('drafting', 'Drafting'), ('needs_revision', 'Needs revision'), ('reviewed', 'Reviewed'), ('ready', 'Ready'), ('submitted', 'Submitted')], default='not_started', max_length=20)),
                ('source_url', models.URLField(blank=True, validators=[common.validators.validate_http_url])),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essay_workspaces', to='university_service.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='EssayRevisionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('structure', 'Structure'), ('clarity', 'Clarity'), ('specificity', 'Specificity'), ('authenticity', 'Authenticity'), ('grammar', 'Grammar'), ('word_count', 'Word count'), ('prompt_fit', 'Prompt fit')], max_length=20)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='todo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_tasks', to='essay_service.essayworkspace')),
            ],
            options={
                'ordering': ('status', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='EssayFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_label', models.CharField(choices=[('weak', 'Weak'), ('developing', 'Developing'), ('solid', 'Solid'), ('strong', 'Strong'), ('excellent', 'Excellent')], max_length=20)),
                ('structure_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('clarity_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('authenticity_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('specificity_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grammar_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prompt_fit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('word_limit_status', models.CharField(choices=[('too_short', 'Too short'), ('within_limit', 'Within limit'), ('too_long', 'Too long')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('revision_tasks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='essay_service.essayworkspace')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='essayworkspace',
            index=models.Index(fields=['user', 'status'], name='essay_servi_user_id_4be634_idx'),
        ),
        migrations.AddIndex(
            model_name='essayrevisiontask',
            index=models.Index(fields=['essay', 'category'], name='essay_servi_essay_i_7c0126_idx'),
        ),
    ]
