# Generated by Django 5.2.15 on 2026-06-28 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roadmap_service', '0001_initial'),
        ('university_service', '0004_university_international_office_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTrackerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_round', models.CharField(choices=[('early_decision', 'Early decision'), ('early_action', 'Early action'), ('restrictive_early_action', 'Restrictive early action'), ('regular_decision', 'Regular decision'), ('rolling', 'Rolling'), ('scholarship', 'Scholarship'), ('other', 'Other')], default='regular_decision', max_length=30)),
                ('status', models.CharField(choices=[('researching', 'Researching'), ('shortlisted', 'Shortlisted'), ('preparing', 'Preparing'), ('applying', 'Applying'), ('submitted', 'Submitted'), ('awaiting_decision', 'Awaiting decision'), ('accepted', 'Accepted'), ('waitlisted', 'Waitlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='researching', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('dream', 'Dream')], default='medium', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('financial_aid_deadline', models.DateField(blank=True, null=True)),
                ('scholarship_deadline', models.DateField(blank=True, null=True)),
                ('essays_status', models.CharField(choices=[('not_started', 'Not started'), ('drafting', 'Drafting'), ('needs_revision', 'Needs revision'), ('ready', 'Ready'), ('submitted', 'Submitted')], default='not_started', max_length=20)),
                ('recommendations_status', models.CharField(choices=[('not_started', 'Not started'), ('requested', 'Requested'), ('received', 'Received'), ('submitted', 'Submitted')], default='not_started', max_length=20)),
                ('test_scores_status', models.CharField(choices=[('not_required', 'Not required'), ('planned', 'Planned'), ('ready', 'Ready'), ('sent', 'Sent')], default='not_required', max_length=20)),
                ('documents_status', models.CharField(choices=[('not_started', 'Not started'), ('collecting', 'Collecting'), ('ready', 'Ready'), ('submitted', 'Submitted')], default='not_started', max_length=20)),
                ('financial_aid_status', models.CharField(choices=[('not_applying', 'Not applying'), ('researching', 'Researching'), ('preparing', 'Preparing'), ('submitted', 'Submitted')], default='not_applying', max_length=20)),
                ('notes', models.TextField(blank=True, max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_items', to='university_service.universityprogram')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_items', to='university_service.university')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('deadline', '-priority', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ApplicationMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('category', models.CharField(choices=[('essays', 'Essays'), ('recommendations', 'Recommendations'), ('tests', 'Tests'), ('financial_aid', 'Financial aid'), ('documents', 'Documents'), ('submission', 'Submission'), ('interview', 'Interview'), ('decision', 'Decision')], max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='todo', max_length=20)),
                ('source_url', models.URLField(blank=True, validators=[common.validators.validate_http_url])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_roadmap_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_milestones', to='roadmap_service.roadmaptask')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='application_service.applicationtrackeritem')),
            ],
            options={
                'ordering': ('due_date', '-created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='applicationtrackeritem',
            index=models.Index(fields=['user', 'status'], name='application_user_id_fc5b09_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationtrackeritem',
            constraint=models.UniqueConstraint(fields=('user', 'university'), name='unique_application_per_university'),
        ),
        migrations.AddIndex(
            model_name='applicationmilestone',
            index=models.Index(fields=['application', 'status'], name='application_applica_555353_idx'),
        ),
    ]
