# Generated by Django 5.2.15 on 2026-06-30 16:58

from decimal import ROUND_HALF_UP, Decimal

from django.db import migrations, models


def _round(value):
    return value.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)


def _infer_scale_type(scale):
    if scale is None:
        return "custom_unknown"
    if scale == Decimal("4"):
        return "4_0"
    if scale == Decimal("5"):
        return "5_0"
    if scale == Decimal("100"):
        return "percentage_100"
    if scale == Decimal("45"):
        return "ib_45"
    return "custom_unknown"


def _percentage_to_gpa(percentage):
    bands = (
        (Decimal("97"), Decimal("4.00")),
        (Decimal("93"), Decimal("3.80")),
        (Decimal("90"), Decimal("3.60")),
        (Decimal("87"), Decimal("3.40")),
        (Decimal("83"), Decimal("3.20")),
        (Decimal("80"), Decimal("3.00")),
        (Decimal("77"), Decimal("2.70")),
        (Decimal("73"), Decimal("2.30")),
        (Decimal("70"), Decimal("2.00")),
        (Decimal("67"), Decimal("1.70")),
        (Decimal("65"), Decimal("1.30")),
        (Decimal("60"), Decimal("1.00")),
    )
    for minimum, gpa in bands:
        if percentage >= minimum:
            return gpa
    return Decimal("0.70")


def backfill_academic_normalization(apps, schema_editor):
    StudentProfile = apps.get_model("user_profile_service", "StudentProfile")
    for profile in StudentProfile.objects.exclude(gpa__isnull=True).exclude(gpa_scale__isnull=True):
        if profile.gpa_scale <= 0 or profile.gpa > profile.gpa_scale:
            continue
        scale_type = _infer_scale_type(profile.gpa_scale)
        percentage = _round(profile.gpa / profile.gpa_scale * Decimal("100"))
        normalized = None
        confidence = "low"
        note = "GPA scale is custom or unknown; UniWay will not compare it as a 4.0 GPA."
        if scale_type == "4_0":
            normalized = _round(profile.gpa)
            confidence = "high"
            note = "GPA is already on a 4.0 scale."
        elif scale_type == "5_0":
            normalized = _round(profile.gpa / profile.gpa_scale * Decimal("4"))
            confidence = "medium"
            note = "Converted proportionally from a 5-point/local scale for comparison only."
        elif scale_type == "percentage_100":
            normalized = _percentage_to_gpa(percentage)
            confidence = "medium"
            note = "Converted conservatively from a 100-point percentage band for comparison only."
        elif scale_type == "ib_45":
            normalized = _round(profile.gpa / profile.gpa_scale * Decimal("4"))
            confidence = "medium"
            note = "Mapped conservatively from IB / 45 bands for comparison only."

        profile.original_gpa_value = profile.gpa
        profile.original_gpa_scale = profile.gpa_scale
        profile.original_gpa_scale_type = scale_type
        profile.normalized_percentage = percentage
        profile.normalized_gpa_4 = normalized
        profile.academic_normalization_confidence = confidence
        profile.academic_normalization_note = note
        profile.save(
            update_fields=[
                "original_gpa_value",
                "original_gpa_scale",
                "original_gpa_scale_type",
                "normalized_percentage",
                "normalized_gpa_4",
                "academic_normalization_confidence",
                "academic_normalization_note",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_service', '0004_structured_profile_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_normalization_confidence',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=12),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='academic_normalization_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='curriculum_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='curriculum_type',
            field=models.CharField(choices=[('local_school', 'Local school'), ('academic_lyceum', 'Academic lyceum'), ('ib', 'IB'), ('a_level', 'A-Level'), ('ap', 'AP'), ('national_diploma', 'National diploma'), ('foundation', 'Foundation'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='normalized_gpa_4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='normalized_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='original_gpa_scale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='original_gpa_scale_type',
            field=models.CharField(choices=[('4_0', '4.0 scale'), ('5_0', '5.0 scale'), ('percentage_100', '100-point percentage'), ('ib_45', 'IB / 45'), ('a_level', 'A-Level'), ('ap_heavy', 'AP-heavy curriculum'), ('uzbekistan_5', 'Uzbekistan 5-point / lyceum scale'), ('kazakhstan_local', 'Kazakhstan local scale'), ('kyrgyzstan_local', 'Kyrgyzstan local scale'), ('tajikistan_local', 'Tajikistan local scale'), ('custom_unknown', 'Custom / unknown')], default='custom_unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='original_gpa_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.RunPython(backfill_academic_normalization, migrations.RunPython.noop),
    ]
