# Generated by Django 5.2.15 on 2026-07-01 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_service', '0005_studentprofile_academic_normalization_confidence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relationship_role', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('planned', 'Planned'), ('requested', 'Requested'), ('confirmed', 'Confirmed'), ('submitted', 'Submitted')], default='not_started', max_length=20)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_recommenders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=150)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hours_per_week', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weeks_per_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('scale', models.CharField(blank=True, choices=[('school', 'School-level'), ('city', 'City-level'), ('regional', 'Regional-level'), ('national', 'National-level'), ('international', 'International-level')], default='school', max_length=20)),
                ('impact_number', models.CharField(blank=True, max_length=100)),
                ('beneficiaries', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True, max_length=1500)),
                ('proof_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_volunteering', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
