# Generated by Django 5.2.15 on 2026-07-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_service', '0006_recommender_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='original_gpa_scale_type',
            field=models.CharField(choices=[('4_0', '4.0 scale'), ('5_0', '5.0 scale'), ('10_0', '10.0 scale'), ('20_0', '20.0 scale'), ('percentage_100', '100-point percentage'), ('ib_45', 'IB / 45'), ('a_level', 'A-Level'), ('ap_heavy', 'AP-heavy curriculum'), ('uzbekistan_5', 'Uzbekistan 5-point / lyceum scale'), ('kazakhstan_local', 'Kazakhstan local scale'), ('kyrgyzstan_local', 'Kyrgyzstan local scale'), ('tajikistan_local', 'Tajikistan local scale'), ('custom_unknown', 'Custom / unknown')], default='custom_unknown', max_length=32),
        ),
    ]
