# Generated by Django 5.2.16 on 2026-07-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_service', '0008_studentprofile_a_level_subjects_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='campus_setting_preference',
            field=models.CharField(choices=[('any', 'Any'), ('urban', 'Urban'), ('suburban', 'Suburban'), ('rural', 'Rural')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='category_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='desired_recommendation_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='institution_type_preference',
            field=models.CharField(choices=[('any', 'Any'), ('public', 'Public'), ('private', 'Private')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_ranking_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_ranking_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='test_optional_preference',
            field=models.BooleanField(default=False),
        ),
    ]
