# Generated by Django 5.2.16 on 2026-07-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_service', '0010_alter_activity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='product_tour_dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
