# Generated by Django 5.2.16 on 2026-07-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_service', '0009_userpreference_campus_setting_preference_and_more'),
        ('user_profile_service', '0012_alter_essaydraft_notes_alter_honor_description_and_more'),
    ]

    operations = [
    ]
