# Generated by Django 5.2.15 on 2026-06-28 05:00

import django.db.models.deletion
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('university_service', '0002_university_acceptance_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='admissions_url',
            field=models.URLField(blank=True, validators=[common.validators.validate_http_url]),
        ),
        migrations.AddField(
            model_name='university',
            name='application_portal_url',
            field=models.URLField(blank=True, validators=[common.validators.validate_http_url]),
        ),
        migrations.AddField(
            model_name='university',
            name='essay_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='financial_aid_url',
            field=models.URLField(blank=True, validators=[common.validators.validate_http_url]),
        ),
        migrations.AddField(
            model_name='university',
            name='ielts_minimum',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='university',
            name='qs_ranking',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='qs_ranking_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='sat_p25',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='sat_p75',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='test_policy',
            field=models.CharField(blank=True, choices=[('required', 'Required'), ('optional', 'Optional'), ('blind', 'Blind'), ('varies', 'Varies by program')], max_length=20),
        ),
        migrations.CreateModel(
            name='UniversityFieldVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('partial', 'Partial'), ('estimated', 'Estimated')], max_length=20)),
                ('source_url', models.URLField(validators=[common.validators.validate_http_url])),
                ('last_verified_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_verifications', to='university_service.university')),
            ],
            options={
                'ordering': ('field_name',),
                'constraints': [models.UniqueConstraint(fields=('university', 'field_name'), name='unique_university_field_verification')],
            },
        ),
    ]
