# Generated by Django 5.2.15 on 2026-06-28 12:22

from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('university_service', '0003_university_admissions_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='international_office_url',
            field=models.URLField(blank=True, validators=[common.validators.validate_http_url]),
        ),
        migrations.AddField(
            model_name='university',
            name='virtual_info_session_url',
            field=models.URLField(blank=True, validators=[common.validators.validate_http_url]),
        ),
    ]
