# Generated by Django 5.2.15 on 2026-06-30 16:58

from decimal import Decimal

from django.db import migrations, models


def backfill_university_costs(apps, schema_editor):
    University = apps.get_model("university_service", "University")
    for university in University.objects.exclude(tuition_amount__isnull=True):
        currency = (university.tuition_currency or "").strip().upper()
        university.tuition_original_amount = university.tuition_amount
        university.tuition_original_currency = currency
        if currency == "USD":
            university.tuition_usd_amount = university.tuition_amount
            university.currency_conversion_rate = Decimal("1.000000")
            university.currency_conversion_confidence = "high"
            university.currency_conversion_source = "Original amount is already USD."
        elif currency:
            university.currency_conversion_confidence = "low"
            university.cost_notes = (
                f"{university.cost_notes}\nUSD conversion not available yet."
            ).strip()
        university.save(
            update_fields=[
                "tuition_original_amount",
                "tuition_original_currency",
                "tuition_usd_amount",
                "currency_conversion_rate",
                "currency_conversion_confidence",
                "currency_conversion_source",
                "cost_notes",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('university_service', '0008_universityimportjob_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='cost_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='currency_conversion_confidence',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='university',
            name='currency_conversion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='currency_conversion_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='currency_conversion_source',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='university',
            name='total_cost_original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='total_cost_original_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='university',
            name='total_cost_usd_amount',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='tuition_original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='tuition_original_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='university',
            name='tuition_usd_amount',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(db_index=True, max_length=10)),
                ('usd_rate', models.DecimalField(decimal_places=6, help_text='USD value of one unit of currency_code.', max_digits=12)),
                ('effective_date', models.DateField(db_index=True)),
                ('source', models.CharField(max_length=240)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-effective_date', 'currency_code'),
                'constraints': [models.UniqueConstraint(fields=('currency_code', 'effective_date', 'source'), name='unique_exchange_rate_source_date')],
            },
        ),
        migrations.RunPython(backfill_university_costs, migrations.RunPython.noop),
    ]
