# Generated by Django 5.2.15 on 2026-07-03 11:10

import django.db.models.deletion
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('university_service', '0009_university_cost_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversitySubjectRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_area', models.CharField(db_index=True, max_length=160)),
                ('major_cluster', models.CharField(blank=True, choices=[('stem', 'STEM'), ('business_economics_finance', 'Business / Economics / Finance'), ('social_sciences', 'Social sciences'), ('humanities', 'Humanities'), ('law_politics_ir', 'Law / Politics / IR'), ('medicine_biology_health', 'Medicine / Biology / Health'), ('engineering', 'Engineering'), ('computer_science_ai_data', 'Computer science / AI / Data'), ('design_arts', 'Design / Arts'), ('education', 'Education'), ('environmental_sustainability', 'Environmental / Sustainability'), ('public_policy_social_impact', 'Public policy / Social impact'), ('psychology_cognitive_science', 'Psychology / Cognitive science'), ('undecided_interdisciplinary', 'Undecided / Interdisciplinary'), ('other', 'Other')], db_index=True, max_length=60)),
                ('rank', models.PositiveIntegerField(db_index=True)),
                ('source_name', models.CharField(db_index=True, max_length=120)),
                ('source_url', models.URLField(validators=[common.validators.validate_http_url])),
                ('ranking_year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('last_verified_date', models.DateField()),
                ('confidence', models.CharField(choices=[('verified', 'Verified'), ('partial', 'Partial'), ('estimated', 'Estimated')], db_index=True, default='partial', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('rank', 'subject_area'),
            },
        ),
        migrations.AlterModelOptions(
            name='universityprogram',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='university',
            name='global_rank',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='national_rank',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='national_ranking_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='university',
            name='ranking_confidence',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='university',
            name='ranking_last_verified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='ranking_source',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='university',
            name='ranking_source_url',
            field=models.URLField(blank=True, validators=[common.validators.validate_http_url]),
        ),
        migrations.AddField(
            model_name='university',
            name='ranking_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='the_rank',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='department_or_school',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='essay_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='interdisciplinary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='last_verified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='major_cluster',
            field=models.CharField(blank=True, choices=[('stem', 'STEM'), ('business_economics_finance', 'Business / Economics / Finance'), ('social_sciences', 'Social sciences'), ('humanities', 'Humanities'), ('law_politics_ir', 'Law / Politics / IR'), ('medicine_biology_health', 'Medicine / Biology / Health'), ('engineering', 'Engineering'), ('computer_science_ai_data', 'Computer science / AI / Data'), ('design_arts', 'Design / Arts'), ('education', 'Education'), ('environmental_sustainability', 'Environmental / Sustainability'), ('public_policy_social_impact', 'Public policy / Social impact'), ('psychology_cognitive_science', 'Psychology / Cognitive science'), ('undecided_interdisciplinary', 'Undecided / Interdisciplinary'), ('other', 'Other')], db_index=True, max_length=60),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='portfolio_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='program_requirements_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='research_heavy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='source_confidence',
            field=models.CharField(blank=True, choices=[('verified', 'Verified'), ('partial', 'Partial'), ('estimated', 'Estimated')], max_length=20),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='source_url',
            field=models.URLField(blank=True, validators=[common.validators.validate_http_url]),
        ),
        migrations.AddField(
            model_name='universityprogram',
            name='stem_heavy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='universityprogram',
            index=models.Index(fields=['university', 'major_cluster'], name='university__univers_724365_idx'),
        ),
        migrations.AddIndex(
            model_name='universityprogram',
            index=models.Index(fields=['portfolio_required', 'major_cluster'], name='university__portfol_559b9f_idx'),
        ),
        migrations.AddField(
            model_name='universitysubjectranking',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_rankings', to='university_service.universityprogram'),
        ),
        migrations.AddField(
            model_name='universitysubjectranking',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_rankings', to='university_service.university'),
        ),
        migrations.AddIndex(
            model_name='universitysubjectranking',
            index=models.Index(fields=['major_cluster', 'rank'], name='university__major_c_451468_idx'),
        ),
        migrations.AddIndex(
            model_name='universitysubjectranking',
            index=models.Index(fields=['source_name', 'rank'], name='university__source__67adc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='universitysubjectranking',
            constraint=models.UniqueConstraint(fields=('university', 'subject_area', 'source_name', 'ranking_year'), name='unique_university_subject_ranking_year'),
        ),
    ]
