# Generated by Django 5.2.15 on 2026-07-07 09:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('university_service', '0010_universitysubjectranking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='activities_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='admissions_cycle_target',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='university',
            name='admissions_website',
            field=models.URLField(blank=True, validators=[common.validators.validate_http_url]),
        ),
        migrations.AddField(
            model_name='university',
            name='essay_drafts_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='honors_olympiads_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='majors_list',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='university',
            name='merit_scholarship_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='need_based_aid_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='other_scholarships_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='portfolio_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='profile_evidence_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='qs_overall_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='research_experience_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='sat_p50',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='scholarship_links_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='university',
            name='standardized_testing_policy_text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='UniversityGuidanceContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_letters', models.TextField(blank=True)),
                ('what_they_look_for', models.TextField(blank=True)),
                ('preferred_student_profile', models.TextField(blank=True)),
                ('who_they_seek', models.TextField(blank=True)),
                ('student_traits_mentioned', models.TextField(blank=True)),
                ('alumni_profile_evidence', models.TextField(blank=True)),
                ('published_admitted_student_essays', models.TextField(blank=True)),
                ('official_admissions_messaging', models.TextField(blank=True)),
                ('student_life_page_signals', models.TextField(blank=True)),
                ('graduate_alumni_outcomes', models.TextField(blank=True)),
                ('sample_admitted_essays', models.TextField(blank=True)),
                ('essay_themes', models.TextField(blank=True)),
                ('research_leadership_themes', models.TextField(blank=True)),
                ('personality_traits_mentioned', models.TextField(blank=True)),
                ('academic_interests_mentioned', models.TextField(blank=True)),
                ('institutional_values', models.TextField(blank=True)),
                ('source_urls', models.TextField(blank=True)),
                ('last_verified_date', models.DateField(blank=True, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=120)),
                ('data_source', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('raw_context_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guidance_context', to='university_service.university')),
            ],
        ),
        migrations.CreateModel(
            name='UniversitySignalWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_evidence_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('activities_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('honors_olympiads_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('research_experience_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('portfolio_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('subject_passion_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('curiosity_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('originality_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('leadership_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('community_impact_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('research_fit_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('olympiads_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('profile_scoring_source', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal_weights', to='university_service.university')),
            ],
        ),
    ]
