# Generated by Django 5.2.16 on 2026-07-17 17:52

from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('university_service', '0016_university_gpa_average_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='cover_image_retrieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='cover_image_source_title',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='university',
            name='cover_image_source_url',
            field=models.URLField(blank=True, validators=[common.validators.validate_http_url]),
        ),
        migrations.AddField(
            model_name='university',
            name='cover_image_url',
            field=models.URLField(blank=True, validators=[common.validators.validate_http_url]),
        ),
    ]
