# Generated by Django 5.2.16 on 2026-07-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university_service', '0017_excludeduniversity_pinneduniversity'),
        ('university_service', '0018_university_cover_image'),
    ]

    operations = [
    ]
