# Generated by Django 5.2.16 on 2026-07-10 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadlines_enabled', models.BooleanField(default=True)),
                ('exams_enabled', models.BooleanField(default=True)),
                ('roadmap_enabled', models.BooleanField(default=True)),
                ('recommendations_essays_enabled', models.BooleanField(default=True)),
                ('essay_reviews_enabled', models.BooleanField(default=True)),
                ('events_enabled', models.BooleanField(default=True)),
                ('organizer_events_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('deadline_upcoming', 'Deadline upcoming'), ('exam_date_upcoming', 'Exam date upcoming'), ('roadmap_task_due_soon', 'Roadmap task due soon'), ('recommendation_missing', 'Recommendation missing'), ('essay_missing', 'Essay missing'), ('essay_review_completed', 'Essay review completed'), ('event_registration_confirmed', 'Event registration confirmed'), ('event_starting_soon', 'Event starting soon'), ('organizer_event_approved', 'Organizer event approved'), ('organizer_event_rejected', 'Organizer event rejected')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], db_index=True, default='unread', max_length=10)),
                ('action_url', models.CharField(blank=True, max_length=300)),
                ('related_entity_type', models.CharField(blank=True, max_length=40)),
                ('related_entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('dedup_key', models.CharField(max_length=255)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_1bdb78_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_2eb75f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'dedup_key'), name='unique_notification_dedup_key_per_user')],
            },
        ),
    ]
