# Generated by Django 5.2.15 on 2026-06-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_content_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialExamDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('SAT', 'SAT'), ('AP', 'AP')], db_index=True, max_length=8)),
                ('name', models.CharField(max_length=160)),
                ('test_date', models.DateField()),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('late_registration_deadline', models.DateField(blank=True, null=True)),
                ('score_release_window', models.CharField(blank=True, max_length=160)),
                ('academic_year', models.CharField(max_length=20)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField()),
                ('last_verified_date', models.DateField()),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('partial', 'Partial'), ('outdated', 'Outdated')], default='partial', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('test_date', 'exam_type'),
                'indexes': [models.Index(fields=['exam_type', 'test_date'], name='exam_conten_exam_ty_cdfb1a_idx'), models.Index(fields=['verification_status', 'last_verified_date'], name='exam_conten_verific_bfe07b_idx')],
            },
        ),
    ]
