# Generated by Django 5.2.16 on 2026-07-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('user_registered', 'User registered'), ('profile_updated', 'Profile updated'), ('profile_assessment_refreshed', 'Profile assessment refreshed'), ('university_viewed', 'University viewed'), ('university_shortlisted', 'University shortlisted'), ('application_created', 'Application created'), ('application_status_changed', 'Application status changed'), ('roadmap_generated', 'Roadmap generated'), ('roadmap_task_completed', 'Roadmap task completed'), ('essay_review_requested', 'Essay review requested'), ('event_registered', 'Event registered'), ('organizer_event_created', 'Organizer event created'), ('notification_read', 'Notification read'), ('notification_archived', 'Notification archived'), ('admin_moderation_action', 'Admin moderation action')], db_index=True, max_length=60),
        ),
    ]
