"""Source-backed seed data for real universities.

Every non-null statistic in REAL_UNIVERSITIES must have a matching entry in
that university's "verifications" list recording exactly where the value was
confirmed (source_url), when (last_verified_date, set globally below), and
how confidently (status: "verified" for a directly-fetched, verbatim-quoted
official page; "partial" for a value relayed through a search-result snippet
of an official source, or arithmetically derived from two verified official
counts, or otherwise short of a full independent re-read).

Fields with no confirmed official source are simply omitted (left null/blank)
rather than estimated or recalled from training data. This file intentionally
leaves many fields empty — that reflects genuine gaps in what each
institution publishes, not a data-entry omission. See docs/DECISIONS.md for
the demo-vs-real data policy this file implements.
"""

from datetime import date

VERIFIED_ON = date(2026, 6, 28)

REAL_UNIVERSITIES = [
    {
        "slug": "university-of-pennsylvania",
        "name": "University of Pennsylvania",
        "country": "United States",
        "city": "Philadelphia",
        "institution_type": "private",
        "official_website": "https://www.upenn.edu",
        "admissions_url": "https://admissions.upenn.edu",
        "financial_aid_url": "https://srfs.upenn.edu",
        "summary": "Private Ivy League research university in Philadelphia, Pennsylvania.",
        "test_policy": "optional",
        "sat_p25": 1510,
        "sat_p75": 1560,
        "scholarship_available": True,
        "application_deadline": date(2027, 1, 5),
        "qs_ranking": 15,
        "qs_ranking_year": 2026,
        "verifications": [
            {
                "field_name": "test_policy",
                "status": "partial",
                "source_url": "https://admissions.upenn.edu/how-to-apply/resources-programs/incoming-class-profile",
                "note": "Class of 2029 profile reports score ranges only for enrolled students who chose to submit, consistent with a test-optional policy.",
            },
            {
                "field_name": "sat_p25",
                "status": "partial",
                "source_url": "https://admissions.upenn.edu/how-to-apply/resources-programs/incoming-class-profile",
                "note": "Middle 50% SAT range reported for the Class of 2029 among students who submitted scores.",
            },
            {
                "field_name": "sat_p75",
                "status": "partial",
                "source_url": "https://admissions.upenn.edu/how-to-apply/resources-programs/incoming-class-profile",
                "note": "Middle 50% SAT range reported for the Class of 2029 among students who submitted scores.",
            },
            {
                "field_name": "scholarship_available",
                "status": "partial",
                "source_url": "https://admissions.upenn.edu/how-to-apply/resources-programs/incoming-class-profile",
                "note": "Class of 2029 profile states an estimated 23% of admits are Pell-eligible, indicating active need-based aid.",
            },
            {
                "field_name": "application_deadline",
                "status": "partial",
                "source_url": "https://ask.admissions.upenn.edu",
                "note": "Penn's applicant FAQ states a Regular Decision deadline of January 5; shown here for the next upcoming cycle.",
            },
            {
                "field_name": "qs_ranking",
                "status": "partial",
                "source_url": "https://www.topuniversities.com/universities/university-pennsylvania",
                "note": "QS World University Rankings 2026 edition; relayed via search results, not independently loaded from topuniversities.com this session.",
            },
        ],
        "data_sources": [
            {
                "source_title": "Penn Admissions — Incoming Class Profile",
                "source_url": "https://admissions.upenn.edu/how-to-apply/resources-programs/incoming-class-profile",
                "is_official": True,
            },
        ],
    },
    {
        "slug": "princeton-university",
        "name": "Princeton University",
        "country": "United States",
        "city": "Princeton",
        "institution_type": "private",
        "official_website": "https://www.princeton.edu",
        "admissions_url": "https://admission.princeton.edu",
        "financial_aid_url": "https://finaid.princeton.edu",
        "summary": "Private Ivy League research university in Princeton, New Jersey.",
        "test_policy": "optional",
        "scholarship_available": True,
        "application_deadline": date(2027, 1, 1),
        "verifications": [
            {
                "field_name": "test_policy",
                "status": "verified",
                "source_url": "https://admission.princeton.edu/apply/standardized-testing",
                "note": "Directly fetched: \"Princeton remains test optional\" for first-year applicants enrolling through fall 2027; Princeton has stated it will require testing again starting with enrollment for fall 2028.",
            },
            {
                "field_name": "scholarship_available",
                "status": "verified",
                "source_url": "https://admission.princeton.edu/apply/admission-statistics",
                "note": "Directly fetched: \"Princeton will meet 100% of your demonstrated financial need with grant aid\"; 69% of the Class of 2029 qualifies for aid and 25% are Pell-eligible.",
            },
            {
                "field_name": "application_deadline",
                "status": "partial",
                "source_url": "https://admission.princeton.edu/apply/first-year-application-dates-deadlines",
                "note": "Princeton's Regular Decision application is due January 1; shown here for the next upcoming cycle.",
            },
        ],
        "data_sources": [
            {
                "source_title": "Princeton Admission — Admission Statistics",
                "source_url": "https://admission.princeton.edu/apply/admission-statistics",
                "is_official": True,
            },
        ],
    },
    {
        "slug": "cornell-university",
        "name": "Cornell University",
        "country": "United States",
        "city": "Ithaca",
        "institution_type": "private",
        "official_website": "https://www.cornell.edu",
        "admissions_url": "https://admissions.cornell.edu",
        "financial_aid_url": "https://finaid.cornell.edu",
        "summary": "Private Ivy League research university in Ithaca, New York, with statutory colleges that receive New York State support.",
        "test_policy": "required",
        "ielts_minimum": 7.5,
        "scholarship_available": True,
        "application_deadline": date(2027, 1, 2),
        "essay_requirements": "A Cornell-specific Writing Supplement is required alongside the Common Application, covering interest in the chosen college or school and intended major; requirements vary by college.",
        "qs_ranking": 16,
        "qs_ranking_year": 2026,
        "verifications": [
            {
                "field_name": "test_policy",
                "status": "verified",
                "source_url": "https://admissions.cornell.edu/how-to-apply/first-year-applicants",
                "note": "Directly fetched: \"All first-year applicants are required to submit standardized test scores when applying to enroll for fall 2026 and beyond.\"",
            },
            {
                "field_name": "essay_requirements",
                "status": "verified",
                "source_url": "https://admissions.cornell.edu/how-to-apply/first-year-applicants",
                "note": "Directly fetched: each college/school has its own supplement, submitted through the Common Application.",
            },
            {
                "field_name": "ielts_minimum",
                "status": "partial",
                "source_url": "https://admissions.cornell.edu/resources/submit-english-language-proficiency",
                "note": "Cornell states a minimum competitive IELTS score of 7.5 for international applicants.",
            },
            {
                "field_name": "scholarship_available",
                "status": "partial",
                "source_url": "https://finaid.cornell.edu",
                "note": "Cornell provides need-based aid only (no merit/athletic/talent aid) and meets 100% of demonstrated need for admitted students who apply for aid by the admission deadline.",
            },
            {
                "field_name": "application_deadline",
                "status": "partial",
                "source_url": "https://admissions.cornell.edu",
                "note": "Common Application deadline of January 2 for Regular Decision; the Cornell-specific Writing Supplement is due January 16. Shown here for the next upcoming cycle.",
            },
            {
                "field_name": "qs_ranking",
                "status": "partial",
                "source_url": "https://www.topuniversities.com/universities/cornell-university",
                "note": "QS World University Rankings 2026 edition; relayed via search results, not independently loaded from topuniversities.com this session.",
            },
        ],
        "data_sources": [
            {
                "source_title": "Cornell Admissions — First-Year Applicants",
                "source_url": "https://admissions.cornell.edu/how-to-apply/first-year-applicants",
                "is_official": True,
            },
        ],
    },
    {
        "slug": "carnegie-mellon-university",
        "name": "Carnegie Mellon University",
        "country": "United States",
        "city": "Pittsburgh",
        "institution_type": "private",
        "official_website": "https://www.cmu.edu",
        "admissions_url": "https://www.cmu.edu/admission",
        "financial_aid_url": "https://www.cmu.edu/sfs",
        "summary": "Private research university in Pittsburgh, Pennsylvania, known for computer science, engineering, and the arts.",
        "test_policy": "varies",
        "ielts_minimum": 7.5,
        "tuition_amount": 67020.00,
        "tuition_currency": "USD",
        "application_deadline": date(2027, 1, 4),
        "qs_ranking": 56,
        "qs_ranking_year": 2026,
        "verifications": [
            {
                "field_name": "test_policy",
                "status": "verified",
                "source_url": "https://www.cmu.edu/admission/admission/standardized-testing",
                "note": "Directly fetched: School of Computer Science requires SAT/ACT; Engineering, Dietrich, Heinz (Information Systems), Mellon College of Science, and Tepper are \"test flexible\" (SAT, ACT, IB, AP, Cambridge A-Level, or French Baccalaureate accepted); College of Fine Arts is test-optional.",
            },
            {
                "field_name": "tuition_amount",
                "status": "verified",
                "source_url": "https://www.cmu.edu/sfs/tuition/undergraduate/2526.html",
                "note": "Directly fetched: undergraduate tuition for 2025-2026 is \"$67,020\"; total cost of attendance for resident first-years is $90,070 on the same page.",
            },
            {
                "field_name": "application_deadline",
                "status": "verified",
                "source_url": "https://www.cmu.edu/admission/admission",
                "note": "Directly fetched Regular Decision deadline \"Jan 4\" (Drama & Music programs use \"Dec 1\" instead); shown here for the next upcoming cycle.",
            },
            {
                "field_name": "ielts_minimum",
                "status": "partial",
                "source_url": "https://www.cmu.edu/admission",
                "note": "CMU states a minimum overall IELTS band score of 7.5 (paper-based or computer-delivered Academic exam).",
            },
            {
                "field_name": "qs_ranking",
                "status": "partial",
                "source_url": "https://www.topuniversities.com/universities/carnegie-mellon-university",
                "note": "QS World University Rankings 2026 edition; relayed via search results, not independently loaded from topuniversities.com this session.",
            },
        ],
        "data_sources": [
            {
                "source_title": "CMU Student Financial Services — Undergraduate Tuition 2025-26",
                "source_url": "https://www.cmu.edu/sfs/tuition/undergraduate/2526.html",
                "is_official": True,
            },
        ],
    },
    {
        "slug": "new-york-university",
        "name": "New York University",
        "country": "United States",
        "city": "New York",
        "institution_type": "private",
        "official_website": "https://www.nyu.edu",
        "admissions_url": "https://www.nyu.edu/admissions/undergraduate-admissions.html",
        "financial_aid_url": "https://www.nyu.edu/admissions/financial-aid-and-scholarships.html",
        "summary": "Private research university based in New York City with additional degree-granting campuses abroad.",
        "test_policy": "optional",
        "scholarship_available": True,
        "qs_ranking": 59,
        "qs_ranking_year": 2026,
        "verifications": [
            {
                "field_name": "test_policy",
                "status": "partial",
                "source_url": "https://www.nyu.edu/admissions/undergraduate-admissions.html",
                "note": "NYU states students applying to start Fall 2026 receive equal consideration whether or not they submit test scores.",
            },
            {
                "field_name": "scholarship_available",
                "status": "partial",
                "source_url": "https://www.nyu.edu/admissions/financial-aid-and-scholarships/applying-as-a-prospective-undergraduate-student/first-year-applicants/the-nyu-promise.html",
                "note": "\"The NYU Promise\" guarantees 100% of demonstrated need met with grants/scholarships for first-year domestic and international students admitted to the New York campus who apply by the aid deadline.",
            },
            {
                "field_name": "qs_ranking",
                "status": "partial",
                "source_url": "https://www.topuniversities.com/universities/new-york-university-nyu",
                "note": "QS World University Rankings 2026 edition; relayed via search results, not independently loaded from topuniversities.com this session.",
            },
        ],
        "data_sources": [
            {
                "source_title": "NYU Admissions — The NYU Promise",
                "source_url": "https://www.nyu.edu/admissions/financial-aid-and-scholarships/applying-as-a-prospective-undergraduate-student/first-year-applicants/the-nyu-promise.html",
                "is_official": True,
            },
        ],
    },
    {
        "slug": "massachusetts-institute-of-technology",
        "name": "Massachusetts Institute of Technology",
        "country": "United States",
        "city": "Cambridge",
        "institution_type": "private",
        "official_website": "https://web.mit.edu",
        "admissions_url": "https://mitadmissions.org",
        "financial_aid_url": "https://sfs.mit.edu",
        "application_portal_url": "https://apply.mitadmissions.org",
        "summary": "Private research university in Cambridge, Massachusetts, focused on science, engineering, and technology.",
        "test_policy": "required",
        "acceptance_rate": 4.60,
        "tuition_amount": 66720.00,
        "tuition_currency": "USD",
        "application_deadline": date(2027, 1, 5),
        "scholarship_available": True,
        "verifications": [
            {
                "field_name": "test_policy",
                "status": "verified",
                "source_url": "https://mitadmissions.org/apply/firstyear/tests-scores/",
                "note": "Directly fetched: \"We require the SAT or the ACT for both prospective first year and transfer students.\"",
            },
            {
                "field_name": "acceptance_rate",
                "status": "verified",
                "source_url": "https://facts.mit.edu/undergraduate-admissions/",
                "note": "Directly fetched, Class of 2029: \"29,281 Applications for first-year admission\"; \"1,334 Offers of admission (4.6%)\".",
            },
            {
                "field_name": "tuition_amount",
                "status": "verified",
                "source_url": "https://sfs.mit.edu/undergraduate-students/the-cost-of-attendance/coa/",
                "note": "Directly fetched 2026-2027 tuition: \"$66,720\"; total cost of attendance $92,760 on the same page (price before financial aid).",
            },
            {
                "field_name": "application_deadline",
                "status": "verified",
                "source_url": "https://mitadmissions.org/apply/firstyear/deadlines-requirements/",
                "note": "Directly fetched: Early Action \"November 1\", Regular Action \"January 5\". Regular Action date shown here for the next upcoming cycle.",
            },
            {
                "field_name": "scholarship_available",
                "status": "partial",
                "source_url": "https://sfs.mit.edu/undergraduate-students/the-cost-of-attendance/making-mit-affordable/",
                "note": "MIT states students from families with annual income under $200,000 typically attend tuition-free, and plans $176 million in need-based scholarships for 2025-2026.",
            },
        ],
        "data_sources": [
            {
                "source_title": "MIT Facts — Undergraduate Admissions",
                "source_url": "https://facts.mit.edu/undergraduate-admissions/",
                "is_official": True,
            },
            {
                "source_title": "MIT Student Financial Services — Cost of Attendance",
                "source_url": "https://sfs.mit.edu/undergraduate-students/the-cost-of-attendance/coa/",
                "is_official": True,
            },
        ],
    },
    {
        "slug": "stanford-university",
        "name": "Stanford University",
        "country": "United States",
        "city": "Stanford",
        "institution_type": "private",
        "official_website": "https://www.stanford.edu",
        "admissions_url": "https://admission.stanford.edu",
        "summary": "Private research university in Stanford, California. Stanford does not publish its undergraduate acceptance rate on its own admissions website; that figure is withheld until the Common Data Set is released, well after each cycle.",
        "verifications": [],
        "data_sources": [
            {
                "source_title": "Stanford Undergraduate Admission",
                "source_url": "https://admission.stanford.edu/",
                "is_official": True,
            },
        ],
    },
    {
        "slug": "harvard-university",
        "name": "Harvard University",
        "country": "United States",
        "city": "Cambridge",
        "institution_type": "private",
        "official_website": "https://www.harvard.edu",
        "admissions_url": "https://college.harvard.edu/admissions",
        "summary": "Private Ivy League research university in Cambridge, Massachusetts.",
        "acceptance_rate": 4.18,
        "scholarship_available": True,
        "verifications": [
            {
                "field_name": "acceptance_rate",
                "status": "partial",
                "source_url": "https://college.harvard.edu/admissions/admissions-statistics",
                "note": "Derived from officially reported Class of 2029 counts (2,003 admitted of 47,893 applicants = 4.18%); Harvard's page reports the counts but does not itself publish a rounded acceptance rate.",
            },
            {
                "field_name": "scholarship_available",
                "status": "verified",
                "source_url": "https://college.harvard.edu/admissions/admissions-statistics",
                "note": "Directly fetched, Class of 2029: \"45%\" of students attend tuition-free and \"26%\" attend completely free.",
            },
        ],
        "data_sources": [
            {
                "source_title": "Harvard College — Admissions Statistics",
                "source_url": "https://college.harvard.edu/admissions/admissions-statistics",
                "is_official": True,
            },
        ],
    },
    {
        "slug": "university-of-toronto",
        "name": "University of Toronto",
        "country": "Canada",
        "city": "Toronto",
        "institution_type": "public",
        "official_website": "https://www.utoronto.ca",
        "admissions_url": "https://future.utoronto.ca",
        "summary": "Public research university with three campuses in the Greater Toronto Area. Admission averages and tuition vary significantly by campus and program and are published per-program rather than as a single university-wide figure.",
        "scholarship_available": True,
        "verifications": [
            {
                "field_name": "scholarship_available",
                "status": "partial",
                "source_url": "https://future.utoronto.ca/admission-awards",
                "note": "U of T Mississauga offers automatic entrance scholarships to admitted students with averages starting at 90%; scholarship structure is campus/program-specific rather than university-wide.",
            },
        ],
        "data_sources": [
            {
                "source_title": "University of Toronto — Future Students",
                "source_url": "https://future.utoronto.ca/",
                "is_official": True,
            },
        ],
    },
    {
        "slug": "university-of-british-columbia",
        "name": "University of British Columbia",
        "country": "Canada",
        "city": "Vancouver",
        "institution_type": "public",
        "official_website": "https://www.ubc.ca",
        "admissions_url": "https://you.ubc.ca",
        "summary": "Public research university with its main campus in Vancouver, British Columbia, and a second campus in Kelowna (UBC Okanagan). Admission averages and tuition vary by faculty/program and are not published as a single university-wide figure.",
        "verifications": [],
        "data_sources": [
            {
                "source_title": "UBC Undergraduate Programs and Admissions",
                "source_url": "https://you.ubc.ca/",
                "is_official": True,
            },
        ],
    },
    {
        "slug": "university-of-oxford",
        "name": "University of Oxford",
        "country": "United Kingdom",
        "city": "Oxford",
        "institution_type": "public",
        "official_website": "https://www.ox.ac.uk",
        "admissions_url": "https://www.ox.ac.uk/admissions/undergraduate",
        "financial_aid_url": "https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/oxford-support",
        "summary": "Collegiate public research university in Oxford, England. Most of Oxford's own admissions pages could not be independently re-fetched this session; only the UCAS application deadline is recorded here with confidence, sourced via search-result relay rather than a direct page read.",
        "application_deadline": date(2026, 10, 15),
        "verifications": [
            {
                "field_name": "application_deadline",
                "status": "partial",
                "source_url": "https://www.ox.ac.uk/admissions/undergraduate/applying-to-oxford/admissions-timeline",
                "note": "UCAS deadline of 15 October (6pm UK time) for the relevant admissions cycle; relayed via search results, not independently loaded this session (ox.ac.uk blocked direct fetches).",
            },
        ],
        "data_sources": [
            {
                "source_title": "Oxford Undergraduate Admissions",
                "source_url": "https://www.ox.ac.uk/admissions/undergraduate",
                "is_official": True,
            },
        ],
    },
    {
        "slug": "university-of-cambridge",
        "name": "University of Cambridge",
        "country": "United Kingdom",
        "city": "Cambridge",
        "institution_type": "public",
        "official_website": "https://www.cam.ac.uk",
        "admissions_url": "https://www.undergraduate.study.cam.ac.uk",
        "financial_aid_url": "https://www.undergraduate.study.cam.ac.uk/international-students/financial-support",
        "summary": "Collegiate public research university in Cambridge, England. Tuition is tiered by home/international status and, for international students, by subject group, so no single tuition figure is recorded here.",
        "ielts_minimum": 7.5,
        "scholarship_available": True,
        "application_deadline": date(2026, 10, 15),
        "qs_ranking": 6,
        "qs_ranking_year": 2026,
        "verifications": [
            {
                "field_name": "ielts_minimum",
                "status": "verified",
                "source_url": "https://www.undergraduate.study.cam.ac.uk/english-language-requirements",
                "note": "Directly fetched: \"IELTS Academic – normally a minimum overall grade of 7.5, usually with 7.0 or above in each element.\"",
            },
            {
                "field_name": "scholarship_available",
                "status": "verified",
                "source_url": "https://www.undergraduate.study.cam.ac.uk/international-students/financial-support",
                "note": "Directly fetched: \"Few full undergraduate scholarships are available – most support is a partial contribution and is means-tested.\"",
            },
            {
                "field_name": "application_deadline",
                "status": "partial",
                "source_url": "https://www.undergraduate.study.cam.ac.uk/apply",
                "note": "UCAS deadline of 15 October for Cambridge undergraduate applications; relayed via search results, not independently re-confirmed by direct fetch this session.",
            },
            {
                "field_name": "qs_ranking",
                "status": "partial",
                "source_url": "https://www.topuniversities.com/universities/university-cambridge",
                "note": "QS World University Rankings 2026 edition; relayed via search results, not independently loaded from topuniversities.com this session.",
            },
        ],
        "data_sources": [
            {
                "source_title": "Cambridge Undergraduate Admissions — English Language Requirements",
                "source_url": "https://www.undergraduate.study.cam.ac.uk/english-language-requirements",
                "is_official": True,
            },
            {
                "source_title": "Cambridge Undergraduate Admissions — International Financial Support",
                "source_url": "https://www.undergraduate.study.cam.ac.uk/international-students/financial-support",
                "is_official": True,
            },
        ],
    },
    {
        "slug": "bocconi-university",
        "name": "Bocconi University",
        "country": "Italy",
        "city": "Milan",
        "institution_type": "private",
        "official_website": "https://www.unibocconi.it/en",
        "admissions_url": "https://www.unibocconi.it/en/applying-bocconi/bachelor-and-law-programs/application-and-admissions",
        "application_portal_url": "https://apply.unibocconi.it",
        "summary": "Private university in Milan, Italy, specializing in economics, management, law, and political science. Admission is based on a standardized test plus GPA from the third-last and second-last years of secondary school.",
        "test_policy": "required",
        "ielts_minimum": 6.5,
        "verifications": [
            {
                "field_name": "test_policy",
                "status": "verified",
                "source_url": "https://www.unibocconi.it/en/applying-bocconi/bachelor-and-law-programs/application-and-admissions",
                "note": "Directly fetched: accepted entrance tests are \"SAT/L-SAT, ACT and the online Bocconi test\"; selection is based on \"admission test performance and the GPA of the third-last and second-last years.\"",
            },
            {
                "field_name": "ielts_minimum",
                "status": "verified",
                "source_url": "https://www.unibocconi.it/en/applying-bocconi/bachelor-and-law-programs/application-and-admissions/english-certificates-accepted-enrollment",
                "note": "Directly fetched, English-taught (B2-level) programs: IELTS \"6.5 with at least 6.0 in every section.\"",
            },
        ],
        "data_sources": [
            {
                "source_title": "Bocconi — Application and Admissions",
                "source_url": "https://www.unibocconi.it/en/applying-bocconi/bachelor-and-law-programs/application-and-admissions",
                "is_official": True,
            },
        ],
    },
    {
        "slug": "national-university-of-singapore",
        "name": "National University of Singapore",
        "country": "Singapore",
        "city": "Singapore",
        "institution_type": "public",
        "official_website": "https://nus.edu.sg",
        "admissions_url": "https://www.nus.edu.sg/oam/admissions",
        "financial_aid_url": "https://nus.edu.sg/oam/financial-aid",
        "application_portal_url": "https://myaces.nus.edu.sg/applicantPortal",
        "summary": "Public autonomous university in Singapore, established as one of Singapore's Local Autonomous Universities.",
        "test_policy": "required",
        "ielts_minimum": 6.5,
        "scholarship_available": True,
        "essay_requirements": "NUS College applicants answer additional questions and submit an essay for holistic assessment; general admission includes five short-response questions on achievements/aptitude rather than a traditional personal statement.",
        "qs_ranking": 8,
        "qs_ranking_year": 2026,
        "verifications": [
            {
                "field_name": "test_policy",
                "status": "verified",
                "source_url": "https://www.nus.edu.sg/oam/admissions",
                "note": "Directly read from the official NUS Undergraduate Prospectus for International Students AY2026/2027 PDF: international qualification routes require AP (min. score 3 per course), ACT (min. composite 29 plus Writing 8), or SAT (min. 600 Reading & Writing / 650 Math), combined with a minimum number of AP courses.",
            },
            {
                "field_name": "ielts_minimum",
                "status": "verified",
                "source_url": "https://www.nus.edu.sg/oam/admissions",
                "note": "Directly read from the official prospectus's English Language Test table: IELTS 6.5 overall, reading and writing for general admission (Law requires 7.0).",
            },
            {
                "field_name": "scholarship_available",
                "status": "verified",
                "source_url": "https://nus.edu.sg/oam/financial-aid",
                "note": "Directly read from the official prospectus: international applicants are automatically considered for named scholarships including the ASEAN Undergraduate Scholarship and the NUS International Undergraduate Scholarship.",
            },
            {
                "field_name": "essay_requirements",
                "status": "verified",
                "source_url": "https://www.nus.edu.sg/oam/admissions",
                "note": "Directly read from the official prospectus's NUS College and Achievements/Aptitude-Based Admissions sections.",
            },
            {
                "field_name": "qs_ranking",
                "status": "verified",
                "source_url": "https://www.nus.edu.sg/oam/admissions",
                "note": "NUS's own official prospectus states: \"1st in Asia, 8th in the world — QS World University Rankings 2026\", corroborated by an NUS news article dated 19 June 2025. Not independently cross-checked against topuniversities.com directly.",
            },
        ],
        "data_sources": [
            {
                "source_title": "NUS Undergraduate Prospectus for International Students, AY2026/2027",
                "source_url": "https://www.nus.edu.sg/oam/admissions",
                "is_official": True,
            },
        ],
    },
    {
        "slug": "kaist",
        "name": "KAIST",
        "country": "South Korea",
        "city": "Daejeon",
        "institution_type": "public",
        "official_website": "https://www.kaist.ac.kr",
        "summary": "Public, government-funded science and technology research university in Daejeon, South Korea. Its official admissions and financial-aid pages could not be reached this session (connection refused on every attempt), so no admissions statistics are recorded here; only the institution's basic identity is confirmed.",
        "verifications": [],
        "data_sources": [],
    },
]
