# Generated by Django 5.2.15 on 2026-06-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmaptask',
            name='source_type',
            field=models.CharField(choices=[('generated', 'Generated'), ('manual', 'Manual'), ('university_deadline', 'University deadline'), ('profile_gap', 'Profile gap'), ('fit_analysis', 'Fit analysis'), ('essay_status', 'Essay status'), ('exam_plan', 'Exam plan'), ('planning_window', 'Planning window'), ('event', 'Event')], default='generated', max_length=20),
        ),
    ]
