# Generated by Django 5.2.15 on 2026-07-01 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_service', '0001_initial'),
        ('roadmap_service', '0002_alter_roadmaptask_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmaptask',
            name='linked_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_tasks', to='application_service.applicationtrackeritem'),
        ),
    ]
