# Generated by Django 5.2.16 on 2026-07-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap_service', '0003_roadmaptask_linked_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmaptask',
            name='estimated_effort',
            field=models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='roadmaptask',
            name='linked_score_dimension',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='roadmaptask',
            name='source_type',
            field=models.CharField(choices=[('generated', 'Generated'), ('manual', 'Manual'), ('university_deadline', 'University deadline'), ('profile_gap', 'Profile gap'), ('fit_analysis', 'Fit analysis'), ('essay_status', 'Essay status'), ('exam_plan', 'Exam plan'), ('planning_window', 'Planning window'), ('event', 'Event'), ('cached_assessment', 'Cached profile assessment')], default='generated', max_length=20),
        ),
    ]
